%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{sigclust2 Tutorial}
%\VignettePackage{sigclust2}

\documentclass{article}

<<style-knitr, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
@

\usepackage{graphicx}

\title{\texttt{sigclust2}: Statistical Significance of Clustering (..part 2)}
\author{Patrick K. Kimes}

\begin{document}

\maketitle

\tableofcontents

\section{Summary}
\Rpackage{sigclust2} includes significance tests for the output of various popular clustering algorithms. The \texttt{sigclust2} approach is conceptually based on the significance testing procedure originally described in \cite{sigclust} and implemented in \CRANpkg{sigclust}. While \CRANpkg{sigclust} was only capable of testing for the significance of two clusters, we generalize the testing approach to a larger number of clusters, as well as the (agglomerative) hierarchical clustering procedure.


\section{Introduction}
Hierarchical clustering is a popular unsupervised learning tool commonly implemented in genomics to identify subgroup behavior in unlabeled data sets, e.g. a cohort of tumor samples. Unlike non-nested/flat clustering, hierarchical clustering does not require pre-specifying the number of subgroups of interest. Furthermore, hierarchical clustering provides an intuitive representation of the clustering results as a binary tree (\emph{dendrogram}). In cluster analysis, a question of substantial interest and importance is that of whether subgroups identified in the data truly exist. In this package, we present Significance for Hierarchical Clustering (SHC, \texttt{sch}), a simulation based hypothesis testing procedure for identifiying significant clustering in a hierarchical cluster.

In this tutorial we describe our algorithm using one of the simulation settings described in the accompanying manuscript. We also provide steps for reproducing the simulation results presented in the manuscript. 


\subsection{Citation} 
The corresponding manuscript is currently under preparation, and should be available on arXiv soon, i.e. mid-October 2014.
\begin{quote}
Kimes, P.K., Hayes, D.N., Liu Y., and Marron, J.S. (2014)
Statistical significance for hierarchical clustering.
\textit{in preparation}.
\end{quote}


\section{\texttt{shc} Implementation}
We first generate a simple toy dataset, consisting of 3 Gaussian subpopulations in 2 dimensions. The dataset is shown below.
<<>>=
library(RColorBrewer)
library(ggplot2)

## generate the dataset
n_k <- 100
p <- 2
data <- cbind(matrix(rnorm(n_k*2) + c(1, 4), nrow=2),
              matrix(rnorm(n_k*2) + c(-2, -2), nrow=2),
              matrix(rnorm(n_k*2) + c(2, -1), nrow=2))
data <- t(data)

## plot the dataset
data_df<- as.data.frame(data)
data_df$group <- factor(rep(1:3, each=n_k))
qplot(data=data_df, x=V1, y=V2, color=group) +
    scale_color_brewer(palette="Set1") +
    theme_bw()
@ 

We apply the significance of hierarchical clustering (SHC) approach the the generated dataset.
<<>>=
library(sigclust2)

## compute significance of clustering
out <- shc(data, "euclidean", "ward")
summary(out)
@ 

The testing procedure may be applied using either \textit{linkage} or the \textit{2-means CI} to measure the strength of clustering. Additionally, while Ward's linkage is the default method for clustering, other dissimilarities and linkages may also be used in the high-dimensional setting, including:
\begin{itemize}
  \item \textbf{dissimilarity}
    \begin{itemize}
      \item Euclidean
      \item Squared Euclidean
    \end{itemize}
  \item \textbf{linkage}
    \begin{itemize}
      \item single linkage
      \item complete linkage
      \item average linkage
      \end{itemize}
\end{itemize}

When the number of observations is much larger than the dimension of the dataset, as in the example, the choice of dissimilarity and linkage is unrestricted.


\section{Visualization}
The results of \Rpackage{sigclust2} may be summarized in a dendrogram.
<<>>=
plot(out)
@


\begin{thebibliography}{9}
\bibitem{sigclust}Liu, Y., Hayes, D. N., Nobel, A., Marron, J. S. (2008) Statistical Significance of Clustering for High-Dimension, Low-Sample Size Data. Journal of the American Statistical Association 103(408), 1281$-$1293.
\bibitem{TCGA}The TCGA Research Network (2012). Comprehensive genomic characterization of squamous cell lung cancers. Nature 489(7417), 519$-$525.

\end{thebibliography} 


\end{document}
